site_name: Tejaswi Samavedula
site_url: https://tejaswisam.github.io/tejaswi/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    logo: fontawesome/solid/w
  font:
    text: Montserrat
    code: Red Hat Mono
  features:
    - toc.integrate
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - header.autohide
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: blue
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tejaswisamavedula/
    - icon: fontawesome/brands/github
      link: https://github.com/tejaswisam
    - icon: fontawesome/solid/paper-plane
      link: mailto:tejaswisamavedula@gmail.com
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
plugins:
  - blog
  - search
  - tags:
      tags_file: tags.md
nav:
  - About: index.md
  - Projects: 
    - projects/index.md
    - TRACE - Tool for Rapid Analysis, Calibration and Evaluation: projects/trace_device/trace_device.md
    - Multi-Utility Measuring Pen (Patent Pending): projects/mum_pen/mum_pen.md
    - Indoor Mapping and Navigation using Crazyflie Nano-drone: projects/crazyflie/crazyflie.md
    - Design and Development of Autonomous Drone: projects/autonomous_drone/autonomous_drone.md
    - Design and Fabrication Payload carrying Quadcopter: projects/quadcopter/quadcopter.md
    - Sweat based athlete exhaustion detection device: projects/athlete/athlete.md
    - Automatic Door System for Visually Impaired: projects/autodoor/autodoor.md
    - Hostel and Mess Complaint Registration System: projects/dbs/dbs.md
    - Miscellaneous Projects: projects/misc/misc.md
  - Research:
    - research/index.md
  - Certifications:
    - certifications/index.md
  - Awards:
    - awards/index.md
  # - Blog:
  #   - blog/index.md